export default function page() {
  return (
    <div>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
      <p>page</p>
    </div>
  );
}
